version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp
      MYSQL_DATABASE: peoplemeals
      MYSQL_USER: user
      MYSQL_PASSWORD: JG4yKk@JAqZp
    ports:
      - 3306:3306
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp

