version: '3.7'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp
      MYSQL_DATABASE: poeplemeals
      MYSQL_USER: user
      MYSQL_PASSWORD: JG4yKk@JAqZp
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

