version: '3.7'

services:

  db:
    image: mysql:5.7
    container_name: peoplemeals_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp
      MYSQL_DATABASE: peoplemeals
      MYSQL_USER: user
      MYSQL_PASSWORD: JG4yKk@JAqZp
    ports:
      - 3306:3306
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  peopleMealsApp:
    image: peoplemeals
    container_name: peoplemeals_app
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/peoplemeals
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=JG4yKk@JAqZp
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_GENERATE-DLL=true
      - SPRING_DATASOURCE_DATABASE-PLATFORM=org.hibernate.dialect.MySQL5InnoDBDialect
    ports:
      - 8080:8080