version: '3.7'

services:

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp
      MYSQL_DATABASE: peoplemeals
      MYSQL_USER: user
      MYSQL_PASSWORD: JG4yKk@JAqZp
    ports:
      - 3306:3306
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 8088:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: JG4yKk@JAqZp

# todo: cannot containerize Application - Bug of DB connection failing
#  peopleMealsApp:
#    image: peoplemeals
#    depends_on:
#      - db
#    links:
#      - db
#    restart: on-failure
#    environment:
##      - SPRING_PROFILES_ACTIVE=dev
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/peoplemeals?autoReconnect=true&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=JG4yKk@JAqZp
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_GENERATE-DLL=true
#      - SPRING_DATASOURCE_DATABASE-PLATFORM=org.hibernate.dialect.MySQL5InnoDBDialect
#    ports:
#      - 8080:8080