
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peoplemeals
    username: user
    password: JG4yKk@JAqZp
    driver-class-name: com.mysql.cj.jdbc.Driver
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  devtools:
#    add-properties: true