spring.datasource.url=jdbc:mysql://localhost:3306/poeplemeals
spring.datasource.username=user
spring.datasource.password=JG4yKk@JAqZp
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    url: jdbc:db://localhost:3306/poeplemeals
    username: user
    password: JG4yKk@JAqZp
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
