
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poeplemeals #sera 'jdbc:db'?
    username: user
    password: JG4yKk@JAqZp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
